version: "3.1"

networks:
  ims-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: car
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - ims-network
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d